### ISSUE TITLE
How to access these files?

### ISSUE THREAD

**Issue by 7yl4r** [ailich/WFS_Multibeam_Metadata#5]
The metadata provides filepaths but it is unclear where the files are hosted.

**Comment by ailich** [comment]
Hi @7yl4r. This was something I developed mainly for myself. I ended up making it public so I could easily share it with other people on the project. Since it was designed for internal usage, the paths refer to where the data can be found on our personal server. I know we are working with NCEI to host some of the data long term but it is not up yet.

**Comment by ailich** [comment]
The ReadMe has been updated to provide information about how to request data
